version: 0.2

env:
  variables:
    AST_CLI_EXE: "/app/bin/cx"
    CX_PROJECT_NAME: "ast-aws-codebuild-demo"
phases:
  pre_build:
    commands:
      - |
        env | sort;
        ${AST_CLI_EXE} scan create \
        --project-name ${CX_PROJECT_NAME} \
        --file-source . \
        --branch ${CODEBUILD_WEBHOOK_HEAD_REF##*/}
